// Generates src/lib/workflowTypes.generated.ts from the Pydantic JSON schemas.
// Run with: npm run generate:types (from frontend/)
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { createRequire } from 'node:module'
import { fileURLToPath } from 'node:url'

const require = createRequire(import.meta.url)
const { quicktype, InputData, JSONSchemaInput } = require('quicktype-core')

const here = dirname(fileURLToPath(import.meta.url))
const frontendRoot = join(here, '..')
const repoRoot = join(frontendRoot, '..')

function loadSchema(name) {
  return JSON.parse(readFileSync(join(repoRoot, 'schema', name), 'utf8'))
}

const inputData = new InputData()
await inputData.addSource(
  'schema',
  { name: 'workflow.Workflow', schema: JSON.stringify(loadSchema('workflow_schema.json')) },
  () => new JSONSchemaInput(),
)
await inputData.addSource(
  'schema',
  { name: 'run.WorkflowRun', schema: JSON.stringify(loadSchema('run_schema.json')) },
  () => new JSONSchemaInput(),
)

const result = await quicktype({
  lang: 'ts',
  inputData,
  // quicktype-core v26 reads renderer options by their dashed CLI names.
  rendererOptions: { 'just-types': true },
})

if (!result || !Array.isArray(result.lines)) {
  throw new Error(`Unexpected quicktype result shape: ${JSON.stringify(Object.keys(result ?? {}))}`)
}

// quicktype renders an open `[property: string]: unknown` index signature on every
// object type (JSON Schema leaves additionalProperties open by default); Pydantic
// models do not store extras, so drop them to keep exact structural types.
const lines = result.lines.filter((l) => l.trim().replace(/;$/, '') !== '[property: string]: unknown')

const header = '// GENERATED by scripts/generate-types.mjs from schema/*.json — DO NOT EDIT.\n'
const body = lines.join('\n')
const outPath = join(frontendRoot, 'src', 'lib', 'workflowTypes.generated.ts')
writeFileSync(outPath, header + body)
console.log(`Wrote ${outPath} (${(header + body).split('\n').length} lines)`)
