// GENERATED by scripts/generate-types.mjs from schema/*.json — DO NOT EDIT.
/**
 * Top-level workflow definition.
 */
export interface Workflow {
    /**
     * Workflow description
     */
    description?: null | string;
    edges?:       Edge[];
    /**
     * Unique workflow identifier
     */
    id:      string;
    models?: ModelConfig[];
    /**
     * Human-readable name
     */
    name:   string;
    nodes?: Node[];
    /**
     * Named prompt templates referenced by agent nodes
     */
    prompts?: PromptDefinition[];
    /**
     * Schema version for migrations
     */
    schema_version?: number;
    /**
     * Registry capability name this workflow was imported from (provenance)
     */
    source_capability?: null | string;
    /**
     * Capability version it was imported at
     */
    source_version?: null | string;
    /**
     * Explicit state schema (auto-inferred if not set)
     */
    state_schema?: null | StateSchema;
    tools?:        ToolDefinition[];
    /**
     * Live ref: at run start, re-resolve this workflow from the registry (newest published
     * version within the same major) instead of using the saved copy
     */
    track_latest?: boolean;
}

/**
 * A connection between two nodes.
 */
export interface Edge {
    /**
     * Condition for conditional edges
     */
    condition?: null | ConditionConfig;
    /**
     * Unique edge identifier
     */
    id: string;
    /**
     * Source handle name: 'default', 'error', or branch name
     */
    source_handle: string;
    /**
     * Source node id
     */
    source_node_id: string;
    /**
     * Target node id
     */
    target_node_id: string;
    /**
     * Edge type
     */
    type?: EdgeType;
}

/**
 * Configuration for a conditional edge or Conditional node.
 */
export interface ConditionConfig {
    description?: null | string;
    /**
     * The condition expression (syntax depends on type)
     */
    expression: string;
    type:       ConditionType;
}

export type ConditionType = "json_path" | "regex" | "llm";

/**
 * Edge type
 */
export type EdgeType = "static" | "conditional" | "error";

/**
 * A model definition that agents can reference.
 */
export interface ModelConfig {
    /**
     * Reference to a secret key (name in secrets store)
     */
    api_key_ref?: null | string;
    /**
     * Base URL for the API (required for openai_compatible)
     */
    base_url?:            null | string;
    default_temperature?: number;
    /**
     * Unique identifier for this model config
     */
    id: string;
    /**
     * Model name/identifier
     */
    model: string;
    /**
     * Human-readable name, e.g. 'Local Llama'
     */
    name: string;
    /**
     * Cost per 1M tokens, e.g. {'input': 0.0, 'output': 0.0}. Local models = $0.
     */
    pricing?: { [key: string]: number } | null;
    /**
     * Provider type
     */
    provider: ModelProvider;
    /**
     * Registry capability name this entry was imported from (provenance)
     */
    source_capability?: null | string;
    /**
     * Capability version it was imported at
     */
    source_version?: null | string;
    /**
     * Whether to track token costs for this model
     */
    track_cost?: boolean;
    /**
     * Live ref: at run start, re-resolve this entry from the registry (newest published version
     * within the same major) instead of using the inlined copy
     */
    track_latest?: boolean;
}

/**
 * Provider type
 */
export type ModelProvider = "openai_compatible" | "anthropic";

/**
 * A node in the workflow graph.
 */
export interface Node {
    /**
     * Node-specific configuration
     */
    config: Config;
    /**
     * Opt in to an error handle so failures can be routed via a type='error' edge
     */
    error_handling?: boolean;
    /**
     * Unique node identifier
     */
    id: string;
    /**
     * Optional display name for canvas and run logs; falls back to the node type name
     */
    label?: null | string;
    /**
     * Position on canvas
     */
    position?: NodePosition;
    /**
     * Node type
     */
    type: NodeType;
}

/**
 * Node-specific configuration
 *
 * Configuration for the Start node.
 *
 * Configuration for the End node.
 *
 * Configuration for an Agent node.
 *
 * Configuration for a Conditional node.
 *
 * Configuration for a Transform node.
 *
 * Configuration for a Human-in-the-Loop node.
 *
 * Configuration for a Custom Function node.
 *
 * Configuration for an Invoke node (calls a registry capability).
 *
 * Tool kind: the tool is executed in place. Workflow kind: at run start the
 * sub-workflow is expanded into the graph around this node (entry gate) and
 * a synthetic invoke_exit node (exit gate); resolved versions are pinned on
 * the run so every rebuild produces an identical structure.
 *
 * Runtime-only exit gate for an expanded invoke region; never saved to workflow JSON.
 */
export interface Config {
    /**
     * Fields that the workflow accepts as input
     *
     * Fields the human is asked to provide
     *
     * State fields the function reads
     */
    input_fields?: Array<HumanInputField | string>;
    /**
     * Fields that the workflow produces as output
     *
     * State fields to write with human input
     *
     * State fields the function writes
     */
    output_fields?: string[];
    /**
     * Maximum agent iterations
     */
    max_iterations?: number;
    /**
     * Reference to a ModelConfig
     */
    model_id?: string;
    /**
     * Reference to a workflow PromptDefinition; when set, its template is the base system prompt
     */
    prompt_ref?: null | string;
    /**
     * Retry configuration
     */
    retry?: null | RetryConfig;
    /**
     * Inlined skills folded into this agent at runtime
     */
    skills?: AgentSkill[];
    /**
     * Registry capability name this entry was imported from (provenance)
     */
    source_capability?: null | string;
    /**
     * Capability version it was imported at
     */
    source_version?: null | string;
    /**
     * System prompt for the agent
     */
    system_prompt?: string;
    /**
     * Override model temperature
     */
    temperature?: number | null;
    /**
     * References to ToolDefinitions this agent can use
     */
    tool_ids?: string[];
    /**
     * Live ref: at run start, re-resolve this agent node from the registry (newest published
     * version within the same major) instead of using the inlined copy
     */
    track_latest?: boolean;
    /**
     * Conditions that determine which branch to take
     */
    conditions?: ConditionConfig[];
    /**
     * Default branch name if no condition matches
     */
    default_branch?: null | string;
    /**
     * Reference to a CustomFunction node for 'custom_function' mode
     */
    custom_function_id?: null | string;
    /**
     * Field mappings for 'mapping' mode
     */
    field_mappings?: FieldMapping[] | null;
    /**
     * Transformation mode
     */
    mode?: Mode;
    /**
     * Name of the output state field to write
     *
     * Parent data key that receives the sub-workflow's final data
     */
    output_field?: string;
    /**
     * Template string for 'template' mode, e.g. 'Hello {{name}}'
     */
    template?: null | string;
    /**
     * Message shown to the human for approval
     */
    approval_message?: null | string;
    /**
     * If true, the human must approve/reject before continuing
     */
    approval_required?: boolean;
    /**
     * If set, the run auto-fails when no human input arrives within this many seconds. None =
     * wait indefinitely.
     *
     * Execution timeout
     */
    timeout_seconds?: number | null;
    /**
     * Python code to execute (sandboxed)
     */
    code?: string;
    /**
     * Capability name, 'owner/name'
     */
    capability?: string;
    /**
     * Maps parent state paths (source) to the capability's declared inputs (target)
     */
    input_mapping?: FieldMapping[];
    /**
     * Also copy the sub's final output string into the parent output
     */
    set_output?: boolean;
    /**
     * Semver or 'latest'
     */
    version?: string;
    /**
     * Id of the invoke node this gate closes
     */
    invoke_id?: string;
}

/**
 * Maps an input state field to an output field.
 */
export interface FieldMapping {
    /**
     * Source state field name
     */
    source: string;
    /**
     * Target output field name
     */
    target: string;
    /**
     * Optional transform expression (template string)
     */
    transform?: null | string;
}

/**
 * A field the human is asked to provide.
 */
export interface HumanInputField {
    /**
     * Human-readable label
     */
    label: string;
    /**
     * Field name
     */
    name: string;
    /**
     * For 'select' type
     */
    options?:  string[] | null;
    required?: boolean;
    /**
     * Input type
     */
    type: HumanInputFieldType;
}

/**
 * Input type
 */
export type HumanInputFieldType = "text" | "textarea" | "select" | "boolean";

/**
 * Transformation mode
 */
export type Mode = "template" | "mapping" | "custom_function";

/**
 * Retry configuration for a node.
 */
export interface RetryConfig {
    /**
     * Base delay in seconds, doubled each retry
     */
    backoff_base?: number;
    /**
     * Enable retries for this node
     */
    enabled?: boolean;
    /**
     * Maximum number of retry attempts
     */
    max_retries?: number;
    /**
     * Error types to retry on
     */
    retry_on?: string[];
}

/**
 * An inlined skill attached to an agent node (imported from a capability).
 *
 * Folded into the agent at runtime: its prompt is appended to the system
 * prompt and its tools are unioned into the agent's tool set.
 */
export interface AgentSkill {
    /**
     * Skill name (provenance)
     */
    name?: null | string;
    /**
     * Instructions folded into the agent's system prompt
     */
    prompt: string;
    /**
     * Registry capability name this entry was imported from (provenance)
     */
    source_capability?: null | string;
    /**
     * Capability version it was imported at
     */
    source_version?: null | string;
    /**
     * References to workflow ToolDefinitions this skill uses
     */
    tool_ids?: string[];
    /**
     * Live ref: at run start, re-resolve this skill from the registry (newest published version
     * within the same major) instead of using the inlined copy
     */
    track_latest?: boolean;
}

/**
 * Position on canvas
 */
export interface NodePosition {
    x?: number;
    y?: number;
}

/**
 * Node type
 */
export type NodeType = "start" | "end" | "agent" | "conditional" | "transform" | "human_in_loop" | "custom_function" | "invoke" | "invoke_exit";

/**
 * A named prompt template stored at workflow level (`prompts[]`), referenced by agent nodes.
 */
export interface PromptDefinition {
    /**
     * Unique identifier within the workflow
     */
    id: string;
    /**
     * Human-readable name
     */
    name?: null | string;
    /**
     * Registry capability name this entry was imported from (provenance)
     */
    source_capability?: null | string;
    /**
     * Capability version it was imported at
     */
    source_version?: null | string;
    /**
     * Template with {{var}} placeholders resolved from state data at runtime
     */
    text: string;
    /**
     * Live ref: at run start, re-resolve this entry from the registry (newest published version
     * within the same major) instead of using the inlined copy
     */
    track_latest?: boolean;
    /**
     * Declared {{var}} placeholders
     */
    variables?: string[];
}

/**
 * The shared state that flows through the workflow.
 */
export interface StateSchema {
    /**
     * All fields in the shared state
     */
    fields?: StateField[];
}

/**
 * A single field in the workflow's shared state.
 */
export interface StateField {
    /**
     * Human-readable description
     */
    description?: null | string;
    /**
     * If type is 'array', the type of array items
     */
    items_type?: StateFieldType | null;
    /**
     * Field name, used by nodes to read/write state
     */
    name: string;
    /**
     * Whether the field must be present
     */
    required?: boolean;
    /**
     * JSON type of the field
     */
    type: StateFieldType;
}

/**
 * JSON type of the field
 */
export type StateFieldType = "string" | "number" | "boolean" | "array" | "object";

/**
 * A tool available to agents. Defined at workflow level, selected per-agent.
 */
export interface ToolDefinition {
    /**
     * Description the LLM uses to decide when to call it
     */
    description: string;
    /**
     * Unique identifier
     */
    id: string;
    /**
     * How the tool is implemented
     */
    implementation: ToolImplementation;
    /**
     * Tool name, shown to the LLM
     */
    name: string;
    /**
     * JSON Schema parameters for the tool
     */
    parameters?: { [key: string]: JSONSchemaParam };
    /**
     * Registry capability name this entry was imported from (provenance)
     */
    source_capability?: null | string;
    /**
     * Capability version it was imported at
     */
    source_version?: null | string;
    /**
     * Live ref: at run start, re-resolve this entry from the registry (newest published version
     * within the same major) instead of using the inlined copy
     */
    track_latest?: boolean;
}

/**
 * How the tool is implemented
 */
export interface ToolImplementation {
    /**
     * Implementation-specific config (code for custom_function, url for http, etc.)
     */
    config?: { [key: string]: unknown };
    type:    ToolImplementationType;
}

export type ToolImplementationType = "builtin" | "custom_function" | "http";

/**
 * A parameter in a tool's JSON Schema.
 */
export interface JSONSchemaParam {
    description?: null | string;
    enum?:        string[] | null;
    required?:    boolean;
    type:         StateFieldType;
}

/**
 * A single execution of a workflow.
 */
export interface WorkflowRun {
    completed_at?:       number | null;
    error?:              null | string;
    estimated_cost_usd?: number;
    events?:             RunEvent[];
    /**
     * Unique run identifier
     */
    id:                   string;
    input_data?:          { [key: string]: unknown };
    output_data?:         { [key: string]: unknown } | null;
    started_at?:          number | null;
    status?:              RunStatus;
    total_tokens_input?:  number;
    total_tokens_output?: number;
    /**
     * Reference to the workflow
     */
    workflow_id: string;
}

/**
 * An event emitted during workflow execution.
 */
export interface RunEvent {
    data?:    { [key: string]: unknown };
    node_id?: null | string;
    /**
     * Unix timestamp
     */
    timestamp: number;
    type:      EventType;
}

export type EventType = "run_start" | "run_end" | "node_start" | "node_end" | "node_error" | "llm_call" | "llm_token" | "tool_call" | "tool_result" | "human_request" | "human_respond" | "human_timeout" | "run_cancelled" | "iteration_limit" | "retry" | "capability_notice";

export type RunStatus = "pending" | "running" | "completed" | "failed" | "cancelled" | "paused";
